In [3]:
import pandas as pd

In [ ]:
df = pd.read_excel("../rekap_anomali_by subsls.xlsx")
df["Grand Total"] = pd.to_numeric(df["Grand Total"], errors="coerce").fillna(0).astype(int)
df["idsls"] = df["idsls"].astype(str)
df["idkec"] = df["idsls"].str[:7]
df.head()

,idkab,idsls,keluarga 1,keluarga 3,keluarga 4,keluarga 5,keluarga 6,keluarga 7,usaha 1,usaha 2,usaha 3,usaha 4,usaha 5,usaha 6,usaha 7,usaha 8,Grand Total,idkec
0,1601,1601052001000100,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,1601052
1,1601,1601052001000200,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,1601052
2,1601,1601052001000300,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1601052
3,1601,1601052001000700,NaN,NaN,NaN,NaN,24.0,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,28,1601052
4,1601,1601052001000800,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,6,1601052

In [4]:
df_top_10_kecamatan = (
    df.sort_values(["idkec", "Grand Total"], ascending=[True, False])
    .groupby("idkec", group_keys=False)
    .head(10)
)

NameError: name 'df' is not defined

In [31]:
df_top_10_kecamatan.to_excel("../top10_anomali_perkecamatan.xlsx")

In [ ]:
df = pd.read_excel("../rekap_status_usaha_by_subsls.xlsx")

df["id_wilayah"] = df["id_wilayah"].astype(str)
df["idkec"] = df["id_wilayah"].str[:7]
df["jumlah_tidak_ditemukan"] = df["Jumlah Usaha Tidak Ditemukan (BKU)"].add(
    df["Jumlah Usaha Tidak Ditemukan (Usaha Keluarga)"], fill_value=0
)

df_sorted = df.sort_values(by="jumlah_tidak_ditemukan", ascending=False)
df_top10_kecamatan = df_sorted.groupby("idkec", group_keys=False).head(10)

In [35]:
df.head()

,id_wilayah,kd_kab,nama_kecamatan,nama_desa,nama_sls,Jumlah UB Prelist Awal,Jumlah UM Prelist Awal,Jumlah UMK Prelist Awal,Jumlah Usaha Ditemukan (BKU),Jumlah Usaha Ditutup (BKU),...,Jumlah Usaha Baru (BKU),Jumlah Keluarga Prelist Awal,Jumlah Usaha Ditemukan (Usaha Keluarga),Jumlah Usaha Tutup (Usaha Keluarga),Jumlah Usaha Ganda (Usaha Keluarga),Jumlah Usaha Tidak Ditemukan (Usaha Keluarga),Jumlah Usaha Baru (Usaha Keluarga),Progres Pendataan Usaha dalam Keluarga,idkec,jumlah_tidak_ditemukan
0,1601000000000000,1601,TIDAK DIKETAHUI,TIDAK DIKETAHUI,TIDAK DIKETAHUI,13.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1601000,NaN
1,1601052001000100,1601,LENGKITI,BANDAR JAYA,RT 01 DUSUN 1,NaN,NaN,23.0,3.0,NaN,...,NaN,63.0,14.0,9.0,NaN,3.0,15.0,29.0,1601052,17.0
2,1601052001000200,1601,LENGKITI,BANDAR JAYA,RT 02 DUSUN 1,NaN,NaN,20.0,1.0,NaN,...,NaN,75.0,17.0,11.0,NaN,3.0,12.0,29.0,1601052,12.0
3,1601052001000300,1601,LENGKITI,BANDAR JAYA,RT 03 DUSUN 1,NaN,NaN,4.0,NaN,NaN,...,1.0,39.0,5.0,NaN,NaN,NaN,1.0,6.0,1601052,NaN
4,1601052001000400,1601,LENGKITI,BANDAR JAYA,RT 04 DUSUN 2,NaN,NaN,13.0,NaN,NaN,...,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,1601052,NaN

In [40]:
df_top10_kecamatan.to_excel("../top10_usaha_tidak_ditemukan_perkec.xlsx")

In [38]:
df_top10_kecamatan_palembang = df_top10_kecamatan[
    df_top10_kecamatan["idkec"] == "1671022"
]

In [39]:
df_top10_kecamatan_palembang

,id_wilayah,kd_kab,nama_kecamatan,nama_desa,nama_sls,Jumlah UB Prelist Awal,Jumlah UM Prelist Awal,Jumlah UMK Prelist Awal,Jumlah Usaha Ditemukan (BKU),Jumlah Usaha Ditutup (BKU),...,Jumlah Usaha Baru (BKU),Jumlah Keluarga Prelist Awal,Jumlah Usaha Ditemukan (Usaha Keluarga),Jumlah Usaha Tutup (Usaha Keluarga),Jumlah Usaha Ganda (Usaha Keluarga),Jumlah Usaha Tidak Ditemukan (Usaha Keluarga),Jumlah Usaha Baru (Usaha Keluarga),Progres Pendataan Usaha dalam Keluarga,idkec,jumlah_tidak_ditemukan
32224,1671022002000300,1671,JAKABARING,TUANKENTANG,RT 003 RW 001,NaN,NaN,82.0,1.0,NaN,...,5.0,105.0,NaN,3.0,NaN,2.0,27.0,27.0,1671022,83.0
32309,1671022004002301,1671,JAKABARING,SILABERANTI,RT 021 RW 005,1.0,NaN,67.0,3.0,NaN,...,13.0,167.0,NaN,NaN,NaN,NaN,36.0,36.0,1671022,52.0
32332,1671022004003800,1671,JAKABARING,SILABERANTI,RT 040 RW 007,NaN,NaN,56.0,NaN,NaN,...,NaN,118.0,NaN,NaN,NaN,NaN,7.0,7.0,1671022,51.0
32306,1671022004002000,1671,JAKABARING,SILABERANTI,RT 018 RW 004,NaN,NaN,71.0,NaN,NaN,...,NaN,190.0,NaN,NaN,NaN,NaN,NaN,NaN,1671022,48.0
32262,1671022003001000,1671,JAKABARING,DELAPAN ULU,RT 010 RW 002,NaN,NaN,66.0,1.0,NaN,...,NaN,146.0,NaN,NaN,NaN,2.0,30.0,30.0,1671022,45.0
32263,1671022003001101,1671,JAKABARING,DELAPAN ULU,RT 011 RW 003,NaN,NaN,45.0,NaN,NaN,...,1.0,427.0,NaN,NaN,NaN,NaN,18.0,18.0,1671022,44.0
32240,1671022002001900,1671,JAKABARING,TUANKENTANG,RT 028 RW 003,NaN,NaN,47.0,NaN,NaN,...,NaN,108.0,NaN,NaN,NaN,1.0,24.0,24.0,1671022,40.0
32304,1671022004001800,1671,JAKABARING,SILABERANTI,RT 016 RW 004,NaN,NaN,61.0,5.0,NaN,...,NaN,132.0,NaN,NaN,NaN,1.0,22.0,22.0,1671022,39.0
32348,1671022005001100,1671,JAKABARING,SEMBILAN SEPULUH ULU,RT 011 RW 003,NaN,1.0,48.0,1.0,NaN,...,NaN,66.0,NaN,NaN,NaN,NaN,30.0,30.0,1671022,36.0
32280,1671022003002500,1671,JAKABARING,DELAPAN ULU,RT 030 RW 005,NaN,NaN,38.0,NaN,NaN,...,NaN,181.0,NaN,NaN,NaN,NaN,NaN,NaN,1671022,36.0