In [1]:
import pandas as pd
from pathlib import Path

In [2]:
folder = Path("../scrap_progres_kbli/")
files = sorted(folder.glob("progres_kbli_*.xlsx"))

total_files = len(files)
list_df = []
total_baris = 0

for i, file in enumerate(files, start=1):
    df_temp = pd.read_excel(file)
    list_df.append(df_temp)

    total_baris += len(df_temp)
    print(f"[{i}/{total_files}] {file.name} -> {len(df_temp)} baris (total sejauh ini: {total_baris})")

df = pd.concat(list_df, ignore_index=True)

print(f"\nTotal file : {len(list_df)}")
print(f"Total baris: {len(df)}")

[1/241] progres_kbli_1601052.xlsx -> 25800 baris (total sejauh ini: 25800)
[2/241] progres_kbli_1601070.xlsx -> 14520 baris (total sejauh ini: 40320)
[3/241] progres_kbli_1601080.xlsx -> 19080 baris (total sejauh ini: 59400)
[4/241] progres_kbli_1601081.xlsx -> 29880 baris (total sejauh ini: 89280)
[5/241] progres_kbli_1601082.xlsx -> 11520 baris (total sejauh ini: 100800)
[6/241] progres_kbli_1601083.xlsx -> 10320 baris (total sejauh ini: 111120)
[7/241] progres_kbli_1601090.xlsx -> 30000 baris (total sejauh ini: 141120)
[8/241] progres_kbli_1601091.xlsx -> 23880 baris (total sejauh ini: 165000)
[9/241] progres_kbli_1601092.xlsx -> 21120 baris (total sejauh ini: 186120)
[10/241] progres_kbli_1601093.xlsx -> 11760 baris (total sejauh ini: 197880)
[11/241] progres_kbli_1601130.xlsx -> 46560 baris (total sejauh ini: 244440)
[12/241] progres_kbli_1601131.xlsx -> 33000 baris (total sejauh ini: 277440)
[13/241] progres_kbli_1601140.xlsx -> 19920 baris (total sejauh ini: 297360)
[14/241] progres_kbli_1602010.xlsx -> 46680 baris (total sejauh ini: 344040)
[15/241] progres_kbli_1602011.xlsx -> 36360 baris (total sejauh ini: 380400)
[16/241] progres_kbli_1602020.xlsx -> 39720 baris (total sejauh ini: 420120)
[17/241] progres_kbli_1602021.xlsx -> 49440 baris (total sejauh ini: 469560)
[18/241] progres_kbli_1602022.xlsx -> 48360 baris (total sejauh ini: 517920)
[19/241] progres_kbli_1602023.xlsx -> 40320 baris (total sejauh ini: 558240)
[20/241] progres_kbli_1602030.xlsx -> 45960 baris (total sejauh ini: 604200)
[21/241] progres_kbli_1602031.xlsx -> 31680 baris (total sejauh ini: 635880)
[22/241] progres_kbli_1602040.xlsx -> 24120 baris (total sejauh ini: 660000)
[23/241] progres_kbli_1602041.xlsx -> 19080 baris (total sejauh ini: 679080)
[24/241] progres_kbli_1602050.xlsx -> 15000 baris (total sejauh ini: 694080)
[25/241] progres_kbli_1602051.xlsx -> 12600 baris (total sejauh ini: 706680)
[26/241] progres_kbli_1602060.xlsx -> 34800 baris (total sejauh ini: 741480)
[27/241] progres_kbli_1602120.xlsx -> 27000 baris (total sejauh ini: 768480)
[28/241] progres_kbli_1602121.xlsx -> 27360 baris (total sejauh ini: 795840)
[29/241] progres_kbli_1602130.xlsx -> 34200 baris (total sejauh ini: 830040)
[30/241] progres_kbli_1602131.xlsx -> 28440 baris (total sejauh ini: 858480)
[31/241] progres_kbli_1602140.xlsx -> 39840 baris (total sejauh ini: 898320)
[32/241] progres_kbli_1603010.xlsx -> 7920 baris (total sejauh ini: 906240)
[33/241] progres_kbli_1603011.xlsx -> 9720 baris (total sejauh ini: 915960)
[34/241] progres_kbli_1603012.xlsx -> 8160 baris (total sejauh ini: 924120)
[35/241] progres_kbli_1603020.xlsx -> 22920 baris (total sejauh ini: 947040)
[36/241] progres_kbli_1603021.xlsx -> 13680 baris (total sejauh ini: 960720)
[37/241] progres_kbli_1603031.xlsx -> 31560 baris (total sejauh ini: 992280)
[38/241] progres_kbli_1603032.xlsx -> 21000 baris (total sejauh ini: 1013280)
[39/241] progres_kbli_1603033.xlsx -> 30120 baris (total sejauh ini: 1043400)
[40/241] progres_kbli_1603040.xlsx -> 40800 baris (total sejauh ini: 1084200)
[41/241] progres_kbli_1603050.xlsx -> 37200 baris (total sejauh ini: 1121400)
[42/241] progres_kbli_1603051.xlsx -> 12360 baris (total sejauh ini: 1133760)
[43/241] progres_kbli_1603060.xlsx -> 39960 baris (total sejauh ini: 1173720)
[44/241] progres_kbli_1603061.xlsx -> 6960 baris (total sejauh ini: 1180680)
[45/241] progres_kbli_1603062.xlsx -> 20640 baris (total sejauh ini: 1201320)
[46/241] progres_kbli_1603070.xlsx -> 28920 baris (total sejauh ini: 1230240)
[47/241] progres_kbli_1603071.xlsx -> 13080 baris (total sejauh ini: 1243320)
[48/241] progres_kbli_1603090.xlsx -> 32880 baris (total sejauh ini: 1276200)
[49/241] progres_kbli_1603091.xlsx -> 24840 baris (total sejauh ini: 1301040)
[50/241] progres_kbli_1603092.xlsx -> 25800 baris (total sejauh ini: 1326840)
[51/241] progres_kbli_1603093.xlsx -> 9840 baris (total sejauh ini: 1336680)
[52/241] progres_kbli_1603094.xlsx -> 5880 baris (total sejauh ini: 1342560)
[53/241] progres_kbli_1603095.xlsx -> 11160 baris (total sejauh ini: 1353720)
[54/241] progres_kbli_1604011.xlsx -> 9360 baris (total sejauh ini: 1363080)
[55/241] progres_kbli_1604012.xlsx -> 7560 baris (total sejauh ini: 1370640)
[56/241] progres_kbli_1604040.xlsx -> 12840 baris (total sejauh ini: 1383480)
[57/241] progres_kbli_1604041.xlsx -> 9000 baris (total sejauh ini: 1392480)
[58/241] progres_kbli_1604042.xlsx -> 8160 baris (total sejauh ini: 1400640)
[59/241] progres_kbli_1604043.xlsx -> 4200 baris (total sejauh ini: 1404840)
[60/241] progres_kbli_1604050.xlsx -> 6600 baris (total sejauh ini: 1411440)
[61/241] progres_kbli_1604051.xlsx -> 14040 baris (total sejauh ini: 1425480)
[62/241] progres_kbli_1604052.xlsx -> 4680 baris (total sejauh ini: 1430160)
[63/241] progres_kbli_1604060.xlsx -> 11040 baris (total sejauh ini: 1441200)
[64/241] progres_kbli_1604061.xlsx -> 11400 baris (total sejauh ini: 1452600)
[65/241] progres_kbli_1604062.xlsx -> 5160 baris (total sejauh ini: 1457760)
[66/241] progres_kbli_1604063.xlsx -> 5880 baris (total sejauh ini: 1463640)
[67/241] progres_kbli_1604111.xlsx -> 15120 baris (total sejauh ini: 1478760)
[68/241] progres_kbli_1604112.xlsx -> 24480 baris (total sejauh ini: 1503240)
[69/241] progres_kbli_1604113.xlsx -> 11880 baris (total sejauh ini: 1515120)
[70/241] progres_kbli_1604114.xlsx -> 6600 baris (total sejauh ini: 1521720)
[71/241] progres_kbli_1604120.xlsx -> 41760 baris (total sejauh ini: 1563480)
[72/241] progres_kbli_1604121.xlsx -> 9360 baris (total sejauh ini: 1572840)
[73/241] progres_kbli_1604122.xlsx -> 8160 baris (total sejauh ini: 1581000)
[74/241] progres_kbli_1604123.xlsx -> 5760 baris (total sejauh ini: 1586760)
[75/241] progres_kbli_1604131.xlsx -> 13800 baris (total sejauh ini: 1600560)
[76/241] progres_kbli_1604132.xlsx -> 10680 baris (total sejauh ini: 1611240)
[77/241] progres_kbli_1604133.xlsx -> 5160 baris (total sejauh ini: 1616400)
[78/241] progres_kbli_1605030.xlsx -> 10560 baris (total sejauh ini: 1626960)
[79/241] progres_kbli_1605031.xlsx -> 8760 baris (total sejauh ini: 1635720)
[80/241] progres_kbli_1605032.xlsx -> 7320 baris (total sejauh ini: 1643040)
[81/241] progres_kbli_1605040.xlsx -> 17160 baris (total sejauh ini: 1660200)
[82/241] progres_kbli_1605041.xlsx -> 7560 baris (total sejauh ini: 1667760)
[83/241] progres_kbli_1605050.xlsx -> 10080 baris (total sejauh ini: 1677840)
[84/241] progres_kbli_1605051.xlsx -> 8520 baris (total sejauh ini: 1686360)
[85/241] progres_kbli_1605060.xlsx -> 9240 baris (total sejauh ini: 1695600)
[86/241] progres_kbli_1605061.xlsx -> 7440 baris (total sejauh ini: 1703040)
[87/241] progres_kbli_1605070.xlsx -> 18720 baris (total sejauh ini: 1721760)
[88/241] progres_kbli_1605071.xlsx -> 14040 baris (total sejauh ini: 1735800)
[89/241] progres_kbli_1605072.xlsx -> 9840 baris (total sejauh ini: 1745640)
[90/241] progres_kbli_1605080.xlsx -> 19560 baris (total sejauh ini: 1765200)
[91/241] progres_kbli_1605090.xlsx -> 25560 baris (total sejauh ini: 1790760)
[92/241] progres_kbli_1606010.xlsx -> 14160 baris (total sejauh ini: 1804920)
[93/241] progres_kbli_1606020.xlsx -> 22200 baris (total sejauh ini: 1827120)
[94/241] progres_kbli_1606021.xlsx -> 12480 baris (total sejauh ini: 1839600)
[95/241] progres_kbli_1606022.xlsx -> 20280 baris (total sejauh ini: 1859880)
[96/241] progres_kbli_1606023.xlsx -> 21360 baris (total sejauh ini: 1881240)
[97/241] progres_kbli_1606030.xlsx -> 23760 baris (total sejauh ini: 1905000)
[98/241] progres_kbli_1606031.xlsx -> 19320 baris (total sejauh ini: 1924320)
[99/241] progres_kbli_1606040.xlsx -> 41520 baris (total sejauh ini: 1965840)
[100/241] progres_kbli_1606041.xlsx -> 19800 baris (total sejauh ini: 1985640)
[101/241] progres_kbli_1606090.xlsx -> 40200 baris (total sejauh ini: 2025840)
[102/241] progres_kbli_1606091.xlsx -> 22320 baris (total sejauh ini: 2048160)
[103/241] progres_kbli_1606092.xlsx -> 32520 baris (total sejauh ini: 2080680)
[104/241] progres_kbli_1606100.xlsx -> 54000 baris (total sejauh ini: 2134680)
[105/241] progres_kbli_1606101.xlsx -> 55800 baris (total sejauh ini: 2190480)
[106/241] progres_kbli_1606102.xlsx -> 41520 baris (total sejauh ini: 2232000)
[107/241] progres_kbli_1607010.xlsx -> 29400 baris (total sejauh ini: 2261400)
[108/241] progres_kbli_1607020.xlsx -> 38640 baris (total sejauh ini: 2300040)
[109/241] progres_kbli_1607021.xlsx -> 13920 baris (total sejauh ini: 2313960)
[110/241] progres_kbli_1607030.xlsx -> 27960 baris (total sejauh ini: 2341920)
[111/241] progres_kbli_1607031.xlsx -> 23880 baris (total sejauh ini: 2365800)
[112/241] progres_kbli_1607032.xlsx -> 23880 baris (total sejauh ini: 2389680)
[113/241] progres_kbli_1607040.xlsx -> 42120 baris (total sejauh ini: 2431800)
[114/241] progres_kbli_1607041.xlsx -> 24240 baris (total sejauh ini: 2456040)
[115/241] progres_kbli_1607050.xlsx -> 83280 baris (total sejauh ini: 2539320)
[116/241] progres_kbli_1607051.xlsx -> 25440 baris (total sejauh ini: 2564760)
[117/241] progres_kbli_1607060.xlsx -> 36360 baris (total sejauh ini: 2601120)
[118/241] progres_kbli_1607061.xlsx -> 29400 baris (total sejauh ini: 2630520)
[119/241] progres_kbli_1607070.xlsx -> 42480 baris (total sejauh ini: 2673000)
[120/241] progres_kbli_1607080.xlsx -> 25200 baris (total sejauh ini: 2698200)
[121/241] progres_kbli_1607081.xlsx -> 37440 baris (total sejauh ini: 2735640)
[122/241] progres_kbli_1607090.xlsx -> 24720 baris (total sejauh ini: 2760360)
[123/241] progres_kbli_1607091.xlsx -> 33600 baris (total sejauh ini: 2793960)
[124/241] progres_kbli_1607100.xlsx -> 21480 baris (total sejauh ini: 2815440)
[125/241] progres_kbli_1607101.xlsx -> 21120 baris (total sejauh ini: 2836560)
[126/241] progres_kbli_1607110.xlsx -> 32160 baris (total sejauh ini: 2868720)
[127/241] progres_kbli_1607111.xlsx -> 16680 baris (total sejauh ini: 2885400)
[128/241] progres_kbli_1608010.xlsx -> 10320 baris (total sejauh ini: 2895720)
[129/241] progres_kbli_1608020.xlsx -> 15240 baris (total sejauh ini: 2910960)
[130/241] progres_kbli_1608021.xlsx -> 12840 baris (total sejauh ini: 2923800)
[131/241] progres_kbli_1608022.xlsx -> 12480 baris (total sejauh ini: 2936280)
[132/241] progres_kbli_1608030.xlsx -> 19680 baris (total sejauh ini: 2955960)
[133/241] progres_kbli_1608040.xlsx -> 5280 baris (total sejauh ini: 2961240)
[134/241] progres_kbli_1608041.xlsx -> 4800 baris (total sejauh ini: 2966040)
[135/241] progres_kbli_1608050.xlsx -> 20520 baris (total sejauh ini: 2986560)
[136/241] progres_kbli_1608051.xlsx -> 8640 baris (total sejauh ini: 2995200)
[137/241] progres_kbli_1608060.xlsx -> 10440 baris (total sejauh ini: 3005640)
[138/241] progres_kbli_1608061.xlsx -> 6720 baris (total sejauh ini: 3012360)
[139/241] progres_kbli_1608070.xlsx -> 7800 baris (total sejauh ini: 3020160)
[140/241] progres_kbli_1608071.xlsx -> 5880 baris (total sejauh ini: 3026040)
[141/241] progres_kbli_1608080.xlsx -> 10920 baris (total sejauh ini: 3036960)
[142/241] progres_kbli_1608090.xlsx -> 9480 baris (total sejauh ini: 3046440)
[143/241] progres_kbli_1608091.xlsx -> 4320 baris (total sejauh ini: 3050760)
[144/241] progres_kbli_1608100.xlsx -> 10440 baris (total sejauh ini: 3061200)
[145/241] progres_kbli_1608101.xlsx -> 5040 baris (total sejauh ini: 3066240)
[146/241] progres_kbli_1608102.xlsx -> 6480 baris (total sejauh ini: 3072720)
[147/241] progres_kbli_1609010.xlsx -> 31440 baris (total sejauh ini: 3104160)
[148/241] progres_kbli_1609011.xlsx -> 15600 baris (total sejauh ini: 3119760)
[149/241] progres_kbli_1609012.xlsx -> 13680 baris (total sejauh ini: 3133440)
[150/241] progres_kbli_1609020.xlsx -> 20520 baris (total sejauh ini: 3153960)
[151/241] progres_kbli_1609030.xlsx -> 22320 baris (total sejauh ini: 3176280)
[152/241] progres_kbli_1609031.xlsx -> 38160 baris (total sejauh ini: 3214440)
[153/241] progres_kbli_1609032.xlsx -> 9120 baris (total sejauh ini: 3223560)
[154/241] progres_kbli_1609040.xlsx -> 20640 baris (total sejauh ini: 3244200)
[155/241] progres_kbli_1609041.xlsx -> 32640 baris (total sejauh ini: 3276840)
[156/241] progres_kbli_1609050.xlsx -> 27000 baris (total sejauh ini: 3303840)
[157/241] progres_kbli_1609051.xlsx -> 27720 baris (total sejauh ini: 3331560)
[158/241] progres_kbli_1609060.xlsx -> 26640 baris (total sejauh ini: 3358200)
[159/241] progres_kbli_1609061.xlsx -> 23040 baris (total sejauh ini: 3381240)
[160/241] progres_kbli_1609070.xlsx -> 24000 baris (total sejauh ini: 3405240)
[161/241] progres_kbli_1609080.xlsx -> 36840 baris (total sejauh ini: 3442080)
[162/241] progres_kbli_1609081.xlsx -> 13920 baris (total sejauh ini: 3456000)
[163/241] progres_kbli_1609090.xlsx -> 19440 baris (total sejauh ini: 3475440)
[164/241] progres_kbli_1609091.xlsx -> 24960 baris (total sejauh ini: 3500400)
[165/241] progres_kbli_1609100.xlsx -> 11400 baris (total sejauh ini: 3511800)
[166/241] progres_kbli_1609101.xlsx -> 15240 baris (total sejauh ini: 3527040)
[167/241] progres_kbli_1610010.xlsx -> 10680 baris (total sejauh ini: 3537720)
[168/241] progres_kbli_1610011.xlsx -> 9840 baris (total sejauh ini: 3547560)
[169/241] progres_kbli_1610012.xlsx -> 7680 baris (total sejauh ini: 3555240)
[170/241] progres_kbli_1610020.xlsx -> 20160 baris (total sejauh ini: 3575400)
[171/241] progres_kbli_1610021.xlsx -> 9960 baris (total sejauh ini: 3585360)
[172/241] progres_kbli_1610030.xlsx -> 9600 baris (total sejauh ini: 3594960)
[173/241] progres_kbli_1610031.xlsx -> 5760 baris (total sejauh ini: 3600720)
[174/241] progres_kbli_1610040.xlsx -> 20640 baris (total sejauh ini: 3621360)
[175/241] progres_kbli_1610041.xlsx -> 11040 baris (total sejauh ini: 3632400)
[176/241] progres_kbli_1610042.xlsx -> 9720 baris (total sejauh ini: 3642120)
[177/241] progres_kbli_1610050.xlsx -> 24240 baris (total sejauh ini: 3666360)
[178/241] progres_kbli_1610051.xlsx -> 11400 baris (total sejauh ini: 3677760)
[179/241] progres_kbli_1610052.xlsx -> 7320 baris (total sejauh ini: 3685080)
[180/241] progres_kbli_1610060.xlsx -> 22920 baris (total sejauh ini: 3708000)
[181/241] progres_kbli_1610061.xlsx -> 26160 baris (total sejauh ini: 3734160)
[182/241] progres_kbli_1610062.xlsx -> 10080 baris (total sejauh ini: 3744240)
[183/241] progres_kbli_1611010.xlsx -> 13920 baris (total sejauh ini: 3758160)
[184/241] progres_kbli_1611020.xlsx -> 9480 baris (total sejauh ini: 3767640)
[185/241] progres_kbli_1611030.xlsx -> 18000 baris (total sejauh ini: 3785640)
[186/241] progres_kbli_1611031.xlsx -> 6360 baris (total sejauh ini: 3792000)
[187/241] progres_kbli_1611040.xlsx -> 9840 baris (total sejauh ini: 3801840)
[188/241] progres_kbli_1611050.xlsx -> 7080 baris (total sejauh ini: 3808920)
[189/241] progres_kbli_1611051.xlsx -> 5160 baris (total sejauh ini: 3814080)
[190/241] progres_kbli_1611060.xlsx -> 6720 baris (total sejauh ini: 3820800)
[191/241] progres_kbli_1611070.xlsx -> 25920 baris (total sejauh ini: 3846720)
[192/241] progres_kbli_1611071.xlsx -> 6600 baris (total sejauh ini: 3853320)
[193/241] progres_kbli_1612010.xlsx -> 36000 baris (total sejauh ini: 3889320)
[194/241] progres_kbli_1612020.xlsx -> 10200 baris (total sejauh ini: 3899520)
[195/241] progres_kbli_1612030.xlsx -> 8400 baris (total sejauh ini: 3907920)
[196/241] progres_kbli_1612040.xlsx -> 9120 baris (total sejauh ini: 3917040)
[197/241] progres_kbli_1612050.xlsx -> 12600 baris (total sejauh ini: 3929640)
[198/241] progres_kbli_1613010.xlsx -> 7200 baris (total sejauh ini: 3936840)
[199/241] progres_kbli_1613020.xlsx -> 13800 baris (total sejauh ini: 3950640)
[200/241] progres_kbli_1613030.xlsx -> 12360 baris (total sejauh ini: 3963000)
[201/241] progres_kbli_1613040.xlsx -> 20280 baris (total sejauh ini: 3983280)
[202/241] progres_kbli_1613050.xlsx -> 9000 baris (total sejauh ini: 3992280)
[203/241] progres_kbli_1613060.xlsx -> 10080 baris (total sejauh ini: 4002360)
[204/241] progres_kbli_1613070.xlsx -> 12720 baris (total sejauh ini: 4015080)
[205/241] progres_kbli_1671010.xlsx -> 24360 baris (total sejauh ini: 4039440)
[206/241] progres_kbli_1671011.xlsx -> 39840 baris (total sejauh ini: 4079280)
[207/241] progres_kbli_1671020.xlsx -> 32280 baris (total sejauh ini: 4111560)
[208/241] progres_kbli_1671021.xlsx -> 33360 baris (total sejauh ini: 4144920)
[209/241] progres_kbli_1671022.xlsx -> 33600 baris (total sejauh ini: 4178520)
[210/241] progres_kbli_1671030.xlsx -> 33480 baris (total sejauh ini: 4212000)
[211/241] progres_kbli_1671031.xlsx -> 31080 baris (total sejauh ini: 4243080)
[212/241] progres_kbli_1671040.xlsx -> 51480 baris (total sejauh ini: 4294560)
[213/241] progres_kbli_1671041.xlsx -> 20640 baris (total sejauh ini: 4315200)
[214/241] progres_kbli_1671050.xlsx -> 34320 baris (total sejauh ini: 4349520)
[215/241] progres_kbli_1671051.xlsx -> 26040 baris (total sejauh ini: 4375560)
[216/241] progres_kbli_1671060.xlsx -> 25680 baris (total sejauh ini: 4401240)
[217/241] progres_kbli_1671061.xlsx -> 40320 baris (total sejauh ini: 4441560)
[218/241] progres_kbli_1671062.xlsx -> 23640 baris (total sejauh ini: 4465200)
[219/241] progres_kbli_1671070.xlsx -> 45840 baris (total sejauh ini: 4511040)
[220/241] progres_kbli_1671071.xlsx -> 30600 baris (total sejauh ini: 4541640)
[221/241] progres_kbli_1671080.xlsx -> 74400 baris (total sejauh ini: 4616040)
[222/241] progres_kbli_1671081.xlsx -> 44880 baris (total sejauh ini: 4660920)
[223/241] progres_kbli_1672010.xlsx -> 5280 baris (total sejauh ini: 4666200)
[224/241] progres_kbli_1672020.xlsx -> 31440 baris (total sejauh ini: 4697640)
[225/241] progres_kbli_1672021.xlsx -> 8160 baris (total sejauh ini: 4705800)
[226/241] progres_kbli_1672030.xlsx -> 14040 baris (total sejauh ini: 4719840)
[227/241] progres_kbli_1672031.xlsx -> 14400 baris (total sejauh ini: 4734240)
[228/241] progres_kbli_1672040.xlsx -> 9120 baris (total sejauh ini: 4743360)
[229/241] progres_kbli_1673010.xlsx -> 7200 baris (total sejauh ini: 4750560)
[230/241] progres_kbli_1673011.xlsx -> 8640 baris (total sejauh ini: 4759200)
[231/241] progres_kbli_1673020.xlsx -> 10800 baris (total sejauh ini: 4770000)
[232/241] progres_kbli_1673030.xlsx -> 19320 baris (total sejauh ini: 4789320)
[233/241] progres_kbli_1673040.xlsx -> 17640 baris (total sejauh ini: 4806960)
[234/241] progres_kbli_1674011.xlsx -> 13680 baris (total sejauh ini: 4820640)
[235/241] progres_kbli_1674012.xlsx -> 8880 baris (total sejauh ini: 4829520)
[236/241] progres_kbli_1674021.xlsx -> 8280 baris (total sejauh ini: 4837800)
[237/241] progres_kbli_1674022.xlsx -> 13560 baris (total sejauh ini: 4851360)
[238/241] progres_kbli_1674031.xlsx -> 13440 baris (total sejauh ini: 4864800)
[239/241] progres_kbli_1674032.xlsx -> 11880 baris (total sejauh ini: 4876680)
[240/241] progres_kbli_1674041.xlsx -> 7320 baris (total sejauh ini: 4884000)
[241/241] progres_kbli_1674042.xlsx -> 14640 baris (total sejauh ini: 4898640)

Total file : 241
Total baris: 4898640

In [3]:
df.head()

,id_wilayah,nama_wilayah,level_wilayah,nama_provinsi,nama_kabupaten,nama_kecamatan,nama_desa,nama_sls,is_agregat,kode_indikator,nama_indikator,satuan,total_value,updated_at,kode_kecamatan
0,1601052001000100,RT 01 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 01 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,23.0,2026-07-13T22:15:11.000Z,1601052
1,1601052001000200,RT 02 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 02 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,22.0,2026-07-13T22:15:11.000Z,1601052
2,1601052001000300,RT 03 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 03 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,6.0,2026-07-13T22:15:11.000Z,1601052
3,1601052001000400,RT 04 DUSUN 2,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 04 DUSUN 2,NaN,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,NaN,NaN,1601052
4,1601052001000500,RT 05 DUSUN 2,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 05 DUSUN 2,NaN,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,NaN,NaN,1601052

In [ ]:
# list_indikator = df["nama_indikator"].dropna().unique()
# df_indikator = pd.DataFrame({"nama_indikator": list_indikator})
# df_indikator = df_indikator.sort_values("nama_indikator").reset_index(drop=True)
# df_indikator.to_excel("../list_nama_indikator.xlsx", index=False)
# print(f"Total indikator unik: {len(df_indikator)}")

PermissionError: [Errno 13] Permission denied: '../list_nama_indikator.xlsx'

In [6]:
indikator_jumlah_usaha = [
    'Jumlah Usaha Kategori KBLI "A"',
    'Jumlah Usaha Kategori KBLI "B"',
    "Jumlah Usaha C",
    "Jumlah Usaha D",
    "Jumlah Usaha E",
    "Jumlah Usaha F",
    "Jumlah Usaha G",
    "Jumlah Usaha H",
    "Jumlah Usaha I",
    "Jumlah Usaha J",
    "Jumlah Usaha K",
    'Jumlah Usaha Kategori KBLI "L" (Aktivitas Keuangan dan Asuransi)',
    "Jumlah Usaha M",
    "Jumlah Usaha N, O",
    "Jumlah Usaha P",
    "Jumlah Usaha Q",
    "Jumlah Usaha R",
    "Jumlah Usaha S, U",
    "Jumlah Usaha T",
    "Jumlah Usaha V",
]

indikator_nilai_tambah = [
    'Nilai Tambah Kategori KBLI "A"',
    "Nilai Tambah B",
    "Nilai Tambah C",
    "Nilai Tambah D",
    "Nilai Tambah E",
    "Nilai Tambah F",
    "Nilai Tambah G",
    "Nilai Tambah H",
    "Nilai Tambah I",
    "Nilai Tambah J",
    "Nilai Tambah K",
    'Nilai Tambah Kategori KBLI "L" (Aktivitas Keuangan dan Asuransi)',
    "Nilai Tambah M",
    "Nilai Tambah N, O",
    "Nilai Tambah P",
    "Nilai Tambah Q",
    "Nilai Tambah R",
    "Nilai Tambah S, U",
    "Nilai Tambah T",
    "Nilai Tambah V",
]
indikator_total_omset = [
    'Total Omzet Kategori KBLI "A"',
    "Total Omzet B",
    "Total Omzet C",
    "Total Omzet D",
    "Total Omzet E",
    "Total Omzet F",
    "Total Omzet G",
    "Total Omzet H",
    "Total Omzet I",
    "Total Omzet J",
    "Total Omzet K",
    'Total Omzet Kategori KBLI "L" (Aktivitas Keuangan dan Asuransi)',
    "Total Omzet M",
    "Total Omzet N, O",
    "Total Omzet P",
    "Total Omzet Q",
    "Total Omzet R",
    "Total Omzet S, U",
    "Total Omzet T",
    "Total Omzet V",
]
indikator_total_output = [
    "Total Output A",
    "Total Output B",
    "Total Output C",
    "Total Output D",
    "Total Output E",
    "Total Output F",
    "Total Output G",
    "Total Output H",
    "Total Output I",
    "Total Output J",
    "Total Output K",
    "Total Output L",
    "Total Output M",
    "Total Output N,O",
    "Total Output P",
    "Total Output Q",
    "Total Output R",
    "Total Output S,U",
    "Total Output T",
    "Total Output V",
]
indikator_tenaga_kerja = [
    "Total Tenaga Kerja A",
    "Total Tenaga Kerja B",
    "Total Tenaga Kerja C",
    "Total Tenaga Kerja D",
    "Total Tenaga Kerja E",
    "Total Tenaga Kerja F",
    "Total Tenaga Kerja G",
    "Total Tenaga Kerja H",
    "Total Tenaga Kerja I",
    "Total Tenaga Kerja J",
    "Total Tenaga Kerja K",
    "Total Tenaga Kerja L",
    "Total Tenaga Kerja M",
    "Total Tenaga Kerja N,O",
    "Total Tenaga Kerja P",
    "Total Tenaga Kerja Q",
    "Total Tenaga Kerja R",
    "Total Tenaga Kerja S,U",
    "Total Tenaga Kerja T",
    "Total Tenaga Kerja V",
]

indikator_total_upah = [
    "Total Upah dan Gaji A",
    "Total Upah dan Gaji B",
    "Total Upah dan Gaji C",
    "Total Upah dan Gaji D",
    "Total Upah dan Gaji E",
    "Total Upah dan Gaji F",
    "Total Upah dan Gaji G",
    "Total Upah dan Gaji H",
    "Total Upah dan Gaji I",
    "Total Upah dan Gaji J",
    "Total Upah dan Gaji K",
    "Total Upah dan Gaji L",
    "Total Upah dan Gaji M",
    "Total Upah dan Gaji N,O",
    "Total Upah dan Gaji P",
    "Total Upah dan Gaji Q",
    "Total Upah dan Gaji R",
    "Total Upah dan Gaji S,U",
    "Total Upah dan Gaji T",
    "Total Upah dan Gaji V",
]

In [7]:
df_jumlah_usaha = df[df["nama_indikator"].isin(indikator_jumlah_usaha)]
print(f"Total baris cocok: {len(df_jumlah_usaha)}")
df_jumlah_usaha_subsls = (
    df_jumlah_usaha.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "jumlah_usaha"})
)
df_jumlah_usaha_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah  jumlah_usaha
0      1601052001000100  RT 01 DUSUN 1          32.0
1      1601052001000200  RT 02 DUSUN 1          30.0
2      1601052001000300  RT 03 DUSUN 1           7.0
3      1601052001000400  RT 04 DUSUN 2           0.0
4      1601052001000500  RT 05 DUSUN 2           0.0
...                 ...            ...           ...
40816  1674042010000200          RT 02           0.0
40817  1674042010000300          RT 03           6.0
40818  1674042010000400          RT 04           0.0
40819  1674042010200100          HUTAN           0.0
40820  1674042010500200      PEMAKAMAN           1.0

[40821 rows x 3 columns]

In [13]:
df_nilai_tambah = df[df["nama_indikator"].isin(indikator_nilai_tambah)]
print(f"Total baris cocok: {len(df_nilai_tambah)}")
df_nilai_tambah_subsls = (
    df_nilai_tambah.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "nilai_tambah"})
)
df_nilai_tambah_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah  nilai_tambah
0      1601052001000100  RT 01 DUSUN 1   809750000.0
1      1601052001000200  RT 02 DUSUN 1   741400000.0
2      1601052001000300  RT 03 DUSUN 1   345000000.0
3      1601052001000400  RT 04 DUSUN 2           0.0
4      1601052001000500  RT 05 DUSUN 2           0.0
...                 ...            ...           ...
40816  1674042010000200          RT 02           0.0
40817  1674042010000300          RT 03    28450000.0
40818  1674042010000400          RT 04           0.0
40819  1674042010200100          HUTAN           0.0
40820  1674042010500200      PEMAKAMAN   221000000.0

[40821 rows x 3 columns]

In [14]:
df_total_omset = df[df["nama_indikator"].isin(indikator_total_omset)]
print(f"Total baris cocok: {len(df_total_omset)}")
df_total_omset_subsls = (
    df_total_omset.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "total_omset"})
)
df_total_omset_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah   total_omset
0      1601052001000100  RT 01 DUSUN 1  1.157500e+09
1      1601052001000200  RT 02 DUSUN 1  9.943000e+08
2      1601052001000300  RT 03 DUSUN 1  4.632000e+08
3      1601052001000400  RT 04 DUSUN 2  0.000000e+00
4      1601052001000500  RT 05 DUSUN 2  0.000000e+00
...                 ...            ...           ...
40816  1674042010000200          RT 02  0.000000e+00
40817  1674042010000300          RT 03  6.636500e+07
40818  1674042010000400          RT 04  0.000000e+00
40819  1674042010200100          HUTAN  0.000000e+00
40820  1674042010500200      PEMAKAMAN  2.500000e+08

[40821 rows x 3 columns]

In [15]:
df_total_output = df[df["nama_indikator"].isin(indikator_total_output)]
print(f"Total baris cocok: {len(df_total_output)}")
df_total_output_subsls = (
    df_total_output.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "total_output"})
)
df_total_output_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah  total_output
0      1601052001000100  RT 01 DUSUN 1  1.044000e+09
1      1601052001000200  RT 02 DUSUN 1  9.543000e+08
2      1601052001000300  RT 03 DUSUN 1  4.532000e+08
3      1601052001000400  RT 04 DUSUN 2  0.000000e+00
4      1601052001000500  RT 05 DUSUN 2  0.000000e+00
...                 ...            ...           ...
40816  1674042010000200          RT 02  0.000000e+00
40817  1674042010000300          RT 03  5.436500e+07
40818  1674042010000400          RT 04  0.000000e+00
40819  1674042010200100          HUTAN  0.000000e+00
40820  1674042010500200      PEMAKAMAN  2.500000e+08

[40821 rows x 3 columns]

In [26]:
df_tenaga_kerja = df[df["nama_indikator"].isin(indikator_tenaga_kerja)]
print(f"Total baris cocok: {len(df_tenaga_kerja)}")
df_tenaga_kerja_subsls = (
    df_tenaga_kerja.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "tenaga_kerja"})
)
df_tenaga_kerja_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah  tenaga_kerja
0      1601052001000100  RT 01 DUSUN 1          56.0
1      1601052001000200  RT 02 DUSUN 1          50.0
2      1601052001000300  RT 03 DUSUN 1          16.0
3      1601052001000400  RT 04 DUSUN 2           0.0
4      1601052001000500  RT 05 DUSUN 2           0.0
...                 ...            ...           ...
40816  1674042010000200          RT 02           0.0
40817  1674042010000300          RT 03           8.0
40818  1674042010000400          RT 04           0.0
40819  1674042010200100          HUTAN           0.0
40820  1674042010500200      PEMAKAMAN           2.0

[40821 rows x 3 columns]

In [28]:
df_total_upah = df[df["nama_indikator"].isin(indikator_total_upah)]
print(f"Total baris cocok: {len(df_total_upah)}")
df_total_upah_subsls = (
    df_total_upah.groupby(["id_wilayah", "nama_wilayah"], as_index=False)[
        "total_value"
    ]
    .sum()
    .rename(columns={"total_value": "total_upah"})
)
df_total_upah_subsls

Total baris cocok: 816440

             id_wilayah   nama_wilayah  total_upah
0      1601052001000100  RT 01 DUSUN 1  53000000.0
1      1601052001000200  RT 02 DUSUN 1  14400000.0
2      1601052001000300  RT 03 DUSUN 1  32000000.0
3      1601052001000400  RT 04 DUSUN 2         0.0
4      1601052001000500  RT 05 DUSUN 2         0.0
...                 ...            ...         ...
40816  1674042010000200          RT 02         0.0
40817  1674042010000300          RT 03  12000000.0
40818  1674042010000400          RT 04         0.0
40819  1674042010200100          HUTAN         0.0
40820  1674042010500200      PEMAKAMAN  60000000.0

[40821 rows x 3 columns]

In [29]:
df_gabung = (
    df_jumlah_usaha_subsls.merge(df_nilai_tambah_subsls, on=["id_wilayah", "nama_wilayah"], how="outer")
    .merge(df_total_omset_subsls, on=["id_wilayah", "nama_wilayah"], how="outer")
    .merge(df_total_output_subsls, on=["id_wilayah", "nama_wilayah"], how="outer")
    .merge(df_tenaga_kerja_subsls, on=["id_wilayah", "nama_wilayah"], how="outer")
    .merge(df_total_upah_subsls, on=["id_wilayah", "nama_wilayah"], how="outer")
)

In [21]:
df_gabung.to_excel("../Rekap Progress Usaha/rekap_nilai_usaha.xlsx")

In [23]:
df_jumlah_usaha

,id_wilayah,nama_wilayah,level_wilayah,nama_provinsi,nama_kabupaten,nama_kecamatan,nama_desa,nama_sls,is_agregat,kode_indikator,nama_indikator,satuan,total_value,updated_at,kode_kecamatan
0,1601052001000100,RT 01 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 01 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,23.0,2026-07-13T22:15:11.000Z,1601052
1,1601052001000200,RT 02 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 02 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,22.0,2026-07-13T22:15:11.000Z,1601052
2,1601052001000300,RT 03 DUSUN 1,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 03 DUSUN 1,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,6.0,2026-07-13T22:15:11.000Z,1601052
3,1601052001000400,RT 04 DUSUN 2,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 04 DUSUN 2,NaN,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,NaN,NaN,1601052
4,1601052001000500,RT 05 DUSUN 2,sub_sls,SUMATERA SELATAN,OGAN KOMERING ULU,LENGKITI,BANDAR JAYA,RT 05 DUSUN 2,NaN,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,NaN,NaN,1601052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4891071,1674042010000200,RT 02,sub_sls,SUMATERA SELATAN,LUBUKLINGGAU,LUBUK LINGGAU UTARA II,KALI SERAYU,RT 02,NaN,11512,Jumlah Usaha V,Usaha,NaN,NaN,1674042
4891072,1674042010000300,RT 03,sub_sls,SUMATERA SELATAN,LUBUKLINGGAU,LUBUK LINGGAU UTARA II,KALI SERAYU,RT 03,NaN,11512,Jumlah Usaha V,Usaha,NaN,NaN,1674042
4891073,1674042010000400,RT 04,sub_sls,SUMATERA SELATAN,LUBUKLINGGAU,LUBUK LINGGAU UTARA II,KALI SERAYU,RT 04,NaN,11512,Jumlah Usaha V,Usaha,NaN,NaN,1674042
4891074,1674042010200100,HUTAN,sub_sls,SUMATERA SELATAN,LUBUKLINGGAU,LUBUK LINGGAU UTARA II,KALI SERAYU,HUTAN,NaN,11512,Jumlah Usaha V,Usaha,NaN,NaN,1674042
4891075,1674042010500200,PEMAKAMAN,sub_sls,SUMATERA SELATAN,LUBUKLINGGAU,LUBUK LINGGAU UTARA II,KALI SERAYU,PEMAKAMAN,NaN,11512,Jumlah Usaha V,Usaha,NaN,NaN,1674042

In [30]:
df_pivot_jumlah_usaha = df_jumlah_usaha.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_jumlah_usaha.columns.name = None

df_pivot_nilai_tambah = df_nilai_tambah.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_nilai_tambah.columns.name = None

df_pivot_total_omset = df_total_omset.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_total_omset.columns.name = None

df_pivot_total_output = df_total_output.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_total_output.columns.name = None

df_pivot_tenaga_kerja = df_tenaga_kerja.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_tenaga_kerja.columns.name = None

df_pivot_total_upah = df_total_upah.pivot_table(
    index=["id_wilayah", "nama_wilayah"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="sum",  # atau 'first', 'mean', dll — lihat penjelasan di bawah
).reset_index()
# Hilangkan nama index kolom bawaan pivot
df_pivot_total_upah.columns.name = None

In [31]:
dict_df = {
    "Jumlah Usaha": df_pivot_jumlah_usaha,
    "Nilai Tambah": df_pivot_nilai_tambah,
    "Total Omset": df_pivot_total_omset,
    "Total Output": df_pivot_total_output,
    "Tenaga Kerja": df_pivot_tenaga_kerja,
    "Total Upah": df_pivot_total_upah,
}

with pd.ExcelWriter(
    "../Rekap Progress Usaha/rekap_pekbli.xlsx", engine="openpyxl"
) as writer:
    for nama_sheet, df in dict_df.items():
        df.to_excel(writer, sheet_name=nama_sheet, index=False)