In [ ]:
import pandas as pd
from datetime import datetime

In [3]:
df = pd.read_json("JSON_USAHA_PERKBLI.json")
df.head()

,id_wilayah,nama_wilayah,level_wilayah,nama_provinsi,nama_kabupaten,nama_kecamatan,nama_desa,nama_sls,is_agregat,kode_indikator,nama_indikator,satuan,total_value,updated_at
0,1671010000000000,ILIR BARAT DUA,kecamatan,SUMATERA SELATAN,PALEMBANG,ILIR BARAT DUA,NaN,NaN,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,8.0,2026-07-05 14:35:17.246000+00:00
1,1671011000000000,GANDUS,kecamatan,SUMATERA SELATAN,PALEMBANG,GANDUS,NaN,NaN,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,217.0,2026-07-05 14:35:17.246000+00:00
2,1671020000000000,SEBERANG ULU SATU,kecamatan,SUMATERA SELATAN,PALEMBANG,SEBERANG ULU SATU,NaN,NaN,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,17.0,2026-07-05 14:35:17.246000+00:00
3,1671021000000000,KERTAPATI,kecamatan,SUMATERA SELATAN,PALEMBANG,KERTAPATI,NaN,NaN,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,201.0,2026-07-05 14:35:17.246000+00:00
4,1671022000000000,JAKABARING,kecamatan,SUMATERA SELATAN,PALEMBANG,JAKABARING,NaN,NaN,1.0,60,"Jumlah Usaha Kategori KBLI ""A""",Usaha,13.0,2026-07-05 14:35:17.246000+00:00

In [4]:
df["nama_indikator"] = df["nama_indikator"].str.replace(
    r'Kategori KBLI\s*"([A-Z])"',  # cari pola: Kategori KBLI "X"
    r"\1",  # ganti dengan huruf X saja
    regex=True,
)
df["total_value"] = df["total_value"].fillna(0).astype(int)

df["id_wilayah_7"] = df["id_wilayah"].astype(str).str[:7]

In [5]:
data_list = df["nama_indikator"].unique().tolist()
data_list

['Jumlah Usaha A',
 'Total Omzet A',
 'Nilai Tambah A',
 'Jumlah Usaha B',
 'Total Omzet B',
 'Nilai Tambah B',
 'Jumlah Usaha C',
 'Total Omzet C',
 'Nilai Tambah C',
 'Jumlah Usaha D',
 'Total Omzet D',
 'Nilai Tambah D',
 'Jumlah Usaha E',
 'Total Omzet E',
 'Nilai Tambah E',
 'Jumlah Usaha F',
 'Total Omzet F',
 'Nilai Tambah F',
 'Jumlah Usaha G',
 'Total Omzet G',
 'Nilai Tambah G',
 'Jumlah Usaha H',
 'Total Omzet H',
 'Nilai Tambah H',
 'Jumlah Usaha I',
 'Total Omzet I',
 'Nilai Tambah I',
 'Jumlah Usaha J',
 'Total Omzet J',
 'Nilai Tambah J',
 'Jumlah Usaha K',
 'Total Omzet K',
 'Nilai Tambah K',
 'Jumlah Usaha L (Aktivitas Keuangan dan Asuransi)',
 'Total Omzet L (Aktivitas Keuangan dan Asuransi)',
 'Nilai Tambah L (Aktivitas Keuangan dan Asuransi)',
 'Jumlah Usaha M',
 'Total Omzet M',
 'Nilai Tambah M',
 'Jumlah Usaha P',
 'Total Omzet Q',
 'Nilai Tambah R',
 'Total Omzet P',
 'Nilai Tambah P',
 'Jumlah Usaha Q',
 'Nilai Tambah Q',
 'Jumlah Usaha R',
 'Total Omzet R',
 'Jumlah Usaha N, O',
 'Total Omzet N, O',
 'Nilai Tambah N, O',
 'Jumlah Usaha S, U',
 'Total Omzet S, U',
 'Nilai Tambah S, U']

In [6]:
# 2. Filter dulu baris "Jumlah Usaha" (kalau memang mau khusus itu saja)
usaha_per_kbli = df[
    df["nama_indikator"].str.contains("Jumlah Usaha", case=False, na=False)
]

# 3. Pivot: nama_indikator jadi kolom, isinya dari total_value
usaha_per_kbli_pivot = usaha_per_kbli.pivot_table(
    index=["nama_kecamatan", "id_wilayah_7"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="first",  # atau 'sum' kalau ada duplikat dan mau dijumlah
).reset_index()

kolom_numerik = usaha_per_kbli_pivot.select_dtypes(include='number').columns
total_row = usaha_per_kbli_pivot[kolom_numerik].sum()
total_row['nama_kecamatan'] = 'Total'
total_row['id_wilayah_7'] = ''

# Gabungkan ke bawah
usaha_per_kbli_pivot = pd.concat(
    [usaha_per_kbli_pivot, total_row.to_frame().T],
    ignore_index=True
)

usaha_per_kbli_pivot

nama_indikator,nama_kecamatan,id_wilayah_7,Jumlah Usaha A,Jumlah Usaha B,Jumlah Usaha C,Jumlah Usaha D,Jumlah Usaha E,Jumlah Usaha F,Jumlah Usaha G,Jumlah Usaha H,Jumlah Usaha I,Jumlah Usaha J,Jumlah Usaha K,Jumlah Usaha L (Aktivitas Keuangan dan Asuransi),Jumlah Usaha M,"Jumlah Usaha N, O",Jumlah Usaha P,Jumlah Usaha Q,Jumlah Usaha R,"Jumlah Usaha S, U"
0,ALANG-ALANG LEBAR,1671081,32,0,168,2,8,8,692,116,189,0,3,2,34,35,0,26,10,3
1,BUKITKECIL,1671041,3,0,86,4,4,1,248,56,173,0,0,2,15,7,0,10,13,1
2,GANDUS,1671011,217,0,124,4,2,6,344,102,164,0,4,0,19,18,0,18,6,2
3,ILIR BARAT DUA,1671010,8,0,104,6,3,3,411,229,242,0,3,1,40,15,0,9,10,5
4,ILIR BARAT SATU,1671040,63,0,126,5,1,5,541,104,358,5,7,10,58,26,0,18,3,12
5,ILIR TIMUR DUA,1671060,59,0,204,4,2,1,585,135,255,0,3,3,84,33,0,22,10,3
6,ILIR TIMUR SATU,1671050,12,0,170,7,3,5,570,148,282,1,3,12,55,14,0,13,10,3
7,ILIR TIMUR TIGA,1671062,9,0,113,0,0,1,287,91,255,0,3,7,54,18,0,9,6,3
8,JAKABARING,1671022,13,0,99,2,2,1,518,136,295,0,3,5,72,11,0,8,6,4
9,KALIDONI,1671061,153,1,218,4,11,7,815,203,308,0,8,13,74,49,0,47,20,3
10,KEMUNING,1671051,19,1,120,2,2,3,558,139,357,5,6,9,151,26,0,14,8,4
11,KERTAPATI,1671021,201,0,95,2,3,3,508,142,215,0,9,3,23,9,0,9,10,2
12,PLAJU,1671031,47,0,160,4,11,8,532,78,197,0,5,6,35,28,0,13,6,2
13,SAKO,1671070,58,1,226,3,6,7,733,183,258,0,6,2,51,37,0,32,20,5
14,SEBERANG ULU DUA,1671030,8,0,115,2,1,7,240,110,116,0,5,1,27,19,0,11,8,4
15,SEBERANG ULU SATU,1671020,17,0,142,1,2,1,540,175,143,1,2,4,32,14,0,7,7,4
16,SEMATANGBORANG,1671071,58,0,148,1,8,4,423,118,152,2,7,0,18,20,0,21,17,10
17,SUKARAMI,1671080,72,0,336,5,4,8,610,132,301,0,13,3,90,32,0,23,20,6
18,Total,,1049,3,2754,58,73,79,9155,2397,4260,14,90,83,932,411,0,310,190,76

In [7]:
omzet_per_kbli = df[
    df["nama_indikator"].str.contains("Total Omzet", case=False, na=False)
]

omzet_per_kbli_pivot = omzet_per_kbli.pivot_table(
    index=["nama_kecamatan", "id_wilayah_7"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="first",
).reset_index()

# --- Hitung ulang total_row khusus untuk omzet ---
kolom_numerik = omzet_per_kbli_pivot.select_dtypes(include="number").columns
total_row = omzet_per_kbli_pivot[kolom_numerik].sum()
total_row["nama_kecamatan"] = "Total"
total_row["id_wilayah_7"] = ""

# Gabungkan ke bawah
omzet_per_kbli_pivot = pd.concat(
    [omzet_per_kbli_pivot, total_row.to_frame().T], ignore_index=True
)

omzet_per_kbli_pivot

nama_indikator,nama_kecamatan,id_wilayah_7,Total Omzet A,Total Omzet B,Total Omzet C,Total Omzet D,Total Omzet E,Total Omzet F,Total Omzet G,Total Omzet H,Total Omzet I,Total Omzet J,Total Omzet K,Total Omzet L (Aktivitas Keuangan dan Asuransi),Total Omzet M,"Total Omzet N, O",Total Omzet P,Total Omzet Q,Total Omzet R,"Total Omzet S, U"
0,ALANG-ALANG LEBAR,1671081,3050470000,0,17837830000,150000000,74600000,1255380000,525998419795,12449790000,18895150000,0,188000000,181000000,1039900000,243464750000,0,1712545000,709500000,84000000
1,BUKITKECIL,1671041,31500000,0,633526385880,58200000,93000000,1000000,106200956000,1192520000,110658613328,0,0,109500000,2013900000,2325200000,0,3525150000,8114200000,28800000
2,GANDUS,1671011,2657074600,0,5993930000,161040000,20520000,335600000,46438485000,5834340000,1838462180000,0,309100000,0,1599000000,3151000000,0,3068428000,150600000,51000000
3,ILIR BARAT DUA,1671010,631344000,0,74150282500,854120000,66480000,68300000,195767911079,7797178000,29005651000,0,110640000,60000000,1708200000,724700000,0,315800000,1288246000,72480000
4,ILIR BARAT SATU,1671040,3363490000,0,18169586000,1502819696,3000000,703000000,1176039390012,193303565000,156841378164,17203600000,433800000,133777970716,15256634193,3791900000,0,2483080000,16400000,2531400000
5,ILIR TIMUR DUA,1671060,2085600000,0,14245073000,41460000,51000000,6000000,849280995001,6109600000,37947754241,0,59000000,58500000,2202950000,4246119487,0,484460000,407000000,153000000
6,ILIR TIMUR SATU,1671050,1003800000,0,17410240009,1191390000,55920000,1545000000,432917968000,6167605000,216993921902,12000000,155000000,572099897616,1545100000,6380800000,0,844500000,3791630000,3679000000
7,ILIR TIMUR TIGA,1671062,1738200000,0,9328768001,0,0,50400000,81460237750,3288568000,48289815872,0,63100000,250900000,2059050000,7615695785,0,29936155865,340000000,413280000
8,JAKABARING,1671022,407800000,0,11310360000,23700000,127500000,800000,577117340667,3471095000,29403031000,0,43318000,232925000,10131382000,21451820067,0,268600000,75800000,61100000
9,KALIDONI,1671061,9703045000,3020000000,43742455000,258000008,543660000,19180004055,1076341097910,107149200259,50514100310,0,946800000,159939419444,3329300000,161950573662,0,28399889000,5594460000,36300000
10,KEMUNING,1671051,1434782100,12000000000,9492022000,4000000,77400000,289600000,527424649406,5422860000,96044056480,257600135,1320500000,3615476285,7416650000,9295604000,0,2477668863,1443600000,49700000
11,KERTAPATI,1671021,2955766000,0,15114019000,15000000,52380000,268400000,72258995000,3543485000,15459803000,0,393180000,1282000000,1070000000,394100000,0,647040000,993800000,30840000
12,PLAJU,1671031,1341790000,0,12101690000,31500000,369150000,190600000,64061863500,1849706000,25399818000,0,504500000,6497000000,704800000,925400000,0,889920000,314000000,126000000
13,SAKO,1671070,3573060000,50000000,23949660000,98200000,247100000,2046600000,299828500000,6777510000,202983768000,0,218100000,56000000,1885285000,6786750000,0,3154740000,924760000,256800000
14,SEBERANG ULU DUA,1671030,1447850000,0,12958494000,52400000,1700000,64500000,21409168000,2091272000,6105863889000,0,76500000,378000000,1153800000,750800000,0,34560245000,416400000,217200000
15,SEBERANG ULU SATU,1671020,462700000,0,3012189625000,9720000,15000000,300000,72710960000,8983979000,18168825000,24000000,150000000,373000000,1024500000,1501490000,0,209360000,493200000,192840000
16,SEMATANGBORANG,1671071,1350300000,0,25694940000,7000000,264500000,496400000,104711568050,3154200000,11940420000,11000000,215000000,0,448500000,560600000,0,351382000,171460000,132325000
17,SUKARAMI,1671080,746493223408,0,55156116000,195200000,88800000,3382469000,764330739000,7134680000,60246334772,0,1298000000,785600000,2388003000,3256300000,0,5651475000,2542800000,448000000
18,Total,,783731795108,15070000000,4012371476390,4653749704,2151710000,29884353055,6994299244170,385721153259,9073118510069,17508200135,6484538000,879697189061,56976954193,478573603001,0,118980438728,27787856000,8564065000

In [8]:
nilai_tambah_per_kbli = df[
    df["nama_indikator"].str.contains("Nilai Tambah", case=False, na=False)
]

nilai_tambah_per_kbli_pivot = nilai_tambah_per_kbli.pivot_table(
    index=["nama_kecamatan", "id_wilayah_7"],
    columns="nama_indikator",
    values="total_value",
    aggfunc="first",  # atau 'sum' kalau ada duplikat dan mau dijumlah
).reset_index()
# --- Hitung ulang total_row khusus untuk omzet ---
kolom_numerik = nilai_tambah_per_kbli_pivot.select_dtypes(include="number").columns
total_row = nilai_tambah_per_kbli_pivot[kolom_numerik].sum()
total_row["nama_kecamatan"] = "Total"
total_row["id_wilayah_7"] = ""

# Gabungkan ke bawah
nilai_tambah_per_kbli_pivot = pd.concat(
    [nilai_tambah_per_kbli_pivot, total_row.to_frame().T], ignore_index=True
)
nilai_tambah_per_kbli_pivot

nama_indikator,nama_kecamatan,id_wilayah_7,Nilai Tambah A,Nilai Tambah B,Nilai Tambah C,Nilai Tambah D,Nilai Tambah E,Nilai Tambah F,Nilai Tambah G,Nilai Tambah H,Nilai Tambah I,Nilai Tambah J,Nilai Tambah K,Nilai Tambah L (Aktivitas Keuangan dan Asuransi),Nilai Tambah M,"Nilai Tambah N, O",Nilai Tambah P,Nilai Tambah Q,Nilai Tambah R,"Nilai Tambah S, U"
0,ALANG-ALANG LEBAR,1671081,2491740000,0,7017991000,67600000,41580000,771680000,161410654712,11045091000,6664500000,0,55720000,43500000,662300000,242948580000,0,1557280000,646200000,79500000
1,BUKITKECIL,1671041,2750000,0,617618764880,38550000,77220000,800000,31329638992,725390000,62706033672,0,0,30500000,1883600000,1845700000,0,3210050000,5396950000,27600000
2,GANDUS,1671011,1749658601,0,2541677000,44680000,20070000,139680000,21172495401,4646150000,1829705562060,0,174150000,0,1227200000,2848290001,0,2629976800,86550000,34500000
3,ILIR BARAT DUA,1671010,315857000,0,71760447500,612840000,41481000,51500000,152762184070,5156954000,16303690598,0,48236000,48500000,1153276000,386210000,0,279260000,809925000,58872000
4,ILIR BARAT SATU,1671040,2151295000,0,8386283000,48800000,2700000,384000000,476724225731,191926181000,82246849906,7375000000,292460000,48985481112,9992504528,2639240000,0,1677640000,6250000,1562315488
5,ILIR TIMUR DUA,1671060,1150353000,0,5478983999,13262000,2540000,0,759613231701,4601320000,17108420836,0,37780000,51700000,1667149992,2757225057,0,401075000,327340000,116400000
6,ILIR TIMUR SATU,1671050,788560000,0,9990625893,1073125000,52100000,457750000,341704613171,4186204000,197790843886,11600000,121240000,459035454432,1200144000,5173120000,0,690930000,2303595000,3654520000
7,ILIR TIMUR TIGA,1671062,737390000,0,3495426989,0,0,44400000,23883586713,2347668000,25127189880,0,6800000,207940000,1304137999,4797540842,0,21091996914,265560000,330024000
8,JAKABARING,1671022,299450000,0,4585400000,16524000,81340000,100000,172513730668,2517727778,15332032988,0,27859000,129085000,6096373000,15667153095,0,235250000,59020000,36500000
9,KALIDONI,1671061,6296091000,702540000,15665938002,39300008,208278000,6499588952,918249447027,50123476255,24221418899,0,426270000,136584529204,2231840000,153990181918,0,19969710600,3389500002,20000000
10,KEMUNING,1671051,1157120000,8136681279,5345992000,2900000,51200000,92000000,392560658402,4228021999,53253352758,229980000,995860000,2360123527,6327600000,8256980000,0,2294149600,1146430000,46399900
11,KERTAPATI,1671021,1756061098,0,11527214000,4000000,37680000,147850000,27068561999,2495514000,5502520600,0,147570000,1128210000,891625000,300200000,0,532640000,330400000,25630000
12,PLAJU,1671031,893380000,0,5116554999,6000000,293850000,162675000,17727261300,1228672999,6958131000,0,156700000,6308600000,606036000,602615000,0,756920000,286600000,112264000
13,SAKO,1671070,2182460000,2000000,13385671162,74440000,131339999,1013850000,233717175962,4505589920,184413502001,0,194800000,51770000,1539775000,4990410000,0,2526390000,685758000,193850000
14,SEBERANG ULU DUA,1671030,436740000,0,6877444499,20400000,1000000,10300000,7058838000,1467361000,6093354448000,0,950000,16725000,431200000,548520000,0,33358433304,383220000,200300000
15,SEBERANG ULU SATU,1671020,298944000,0,605137512999,9096000,6400000,0,22540243986,6248841999,10700162001,22800000,63500000,139699999,575799997,731222000,0,178972000,417500000,135640000
16,SEMATANGBORANG,1671071,887708000,0,18832322000,3800000,245700000,296750000,50991706027,2045896000,4108832999,6600000,109310000,0,389760000,453460000,0,296352000,153908000,96700000
17,SUKARAMI,1671080,6047491000,0,30882572999,63250000,68100000,2242713000,688443467999,5252612998,26625085209,0,658040000,774150000,1693757000,2631660000,0,4543150000,1949940000,329100000
18,Total,,29643048699,8841221279,1443646822921,2138567008,1362578999,12315636952,4499471721861,304748672948,8662122577293,7645980000,3517245000,655895968274,39874078516,451568307913,0,96230176218,18644646002,7060115388

In [12]:
sheets = {
    "Jumlah Usaha": usaha_per_kbli_pivot,
    "Total Omzet": omzet_per_kbli_pivot,
    "Nilai Tambah": nilai_tambah_per_kbli_pivot,
}
tanggal_hari_ini = datetime.now().strftime("%d-%m-%Y")
with pd.ExcelWriter(f"rekap_perkbli_{tanggal_hari_ini}.xlsx", engine="openpyxl") as writer:
    for sheet_name, df_sheet in sheets.items():
        df_sheet.to_excel(writer, sheet_name=sheet_name, index=False)